Avoid set-coding-priority for Emacs 28
kazu-yamamoto/Mew pull request #143
Opened 2020-08-28 14:35 UTC by tats

On a recent Emacs 28.0.50, C-c C-l (mew-summary-convert-local-cs) fails
with the error: (void-function set-coding-priority), because the
set-coding-priority function obsolete since Emacs 23.1 have been removed.
cf. http://git.savannah.gnu.org/cgit/emacs.git/commit/?id=874ba85363e90a54f976af542e9b3f4c662e317e

2020-12-01 06:29 UTC, kazu-yamamoto requested changes
Let's remove `#'` if possible.

2020-12-01 11:25 UTC, tats commented on mew-env.el
> +	   (mapcar #'(lambda (x) (symbol-value x)) pri))))
> Let's remove `#'` if possible.

Done.  (rebased and force pushed)

2020-12-02 02:00 UTC, kazu-yamamoto approved these changes
Now LGTM.

2020-12-02 02:03 UTC, merged

2020-12-02 02:03 UTC, kazu-yamamoto commented
Merged. Thank you for your contribution!